source 'http://rubygems.org'

gem 'rake',          '~> 0.8.7'
gem 'thor',          '~> 0.15.4'
gem 'json',          '~> 1.7.3'
gem 'rspec',         '~> 2.11.0'
gem 'guard',         '~>1.2.3'
gem 'guard-bundler', '~> 1.0.0'
gem 'guard-rspec',   '~> 1.2.0'
gem 'simplecov',     '~> 0.6.4'
gem 'open_lighting', '~> 0.1.0'
# gem 'open_lighting', :git => 'https://github.com/marshally/open_lighting_rb.git'
# gem 'open_lighting', :path => ENV['HOME'] + '/Projects/open_lighting'

# not used
# gem 'guard-rack'
# gem 'sinatra'
# gem 'eventmachine'
# gem 'haml'
# gem 'sinatra-contrib'
